### ISSUE TITLE
Can't work with symlink to serial port

### ISSUE THREAD

**Issue by rshym** [xen-troops/rcar_flash#20]
Script can't handle symlink to the serial port. See the below log for case, when `/dev/ttyGEN3` is used for `/dev/ttyUSB?`.

```
sudo ./rcar_flash.py flash -s /dev/ttyGEN3 -c -b h3ulcb_4x2 -p ../ipl-gen3/ all
[INFO] Reading config for board h3ulcb_4x2
[INFO] We are going to flash the following loaders
[INFO] ---
[INFO] bootparam                : ../ipl-gen3/bootparam_sa0-4x2g.srec
[INFO] bl2                      : ../ipl-gen3/bl2-h3ulcb-4x2g.srec
[INFO] cert_header              : ../ipl-gen3/cert_header_sa6-4x2g.srec
[INFO] bl31                     : ../ipl-gen3/bl31-h3ulcb-4x2g.srec
[INFO] tee                      : ../ipl-gen3/tee-h3ulcb.srec
[INFO] u-boot                   : ../ipl-gen3/u-boot-elf.srec
[INFO] ---
[INFO] CPLD SPI protocol does not support revision check
[INFO] CPLD: Issuing command serial_mode
[INFO] CPLD: Issuing command reset
[INFO] Using serial port /dev/ttyGEN3 with baudrate 115200
[CRITICAL] [Errno 2] could not open port /dev/ttyGEN3: [Errno 2] No such file or directory: '/dev/ttyGEN3'
[CRITICAL] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyGEN3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./rcar_flash.py", line 705, in <module>
    main()
  File "./rcar_flash.py", line 103, in main
    actions[args.action](config, args)
  File "./rcar_flash.py", line 216, in do_flash
    conn = open_connection(board, args)
  File "./rcar_flash.py", line 338, in open_connection
    conn = serial.Serial(port=dev_name, baudrate=baud, timeout=20)
  File "/usr/local/lib/python3.8/dist-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/usr/local/lib/python3.8/dist-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyGEN3: [Errno 2] No such file or directory: '/dev/ttyGEN3'
```

**Comment by rshym** [comment]
Can't reproduce the issue on the testrpi12 with the Spider 1.0.

The script works as expected with:
- /dev/ttyUSB0 (original serial port)
- /dev/ttySP0 (created by the udev rule)
- /dev/ttySP0_my (symlink to ttySP0 created by `sudo ln -s /dev/ttySP0 /dev/ttySP0_my`)
